repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: ["--fix"]
        files: '^src/'
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: mypy-local
        name: mypy (src only)
        entry: mypy
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: ["mypy"]
        args: [
          "--ignore-missing-imports",
          "src",
        ]