[mypy]
ignore_missing_imports = True
follow_imports = silent
check_untyped_defs = False
disallow_untyped_defs = False
warn_unused_ignores = False
namespace_packages = True

# Limit files to the main source tree to avoid legacy archives noise
files = src
