# Recovery copy of src/envs/hns_environment.py (pre-restore)
# Generated by assistant

import logging

# src/envs/hns_environment.py
# hns_environment.py v4.5９
import math

import gymnasium as gym
import mujoco
import mujoco.viewer
import numpy as np
import torch
from gymnasium import spaces
from numba import njit

from agents.scripted_agents import RuleBasedHider, RuleBasedSeeker
from core.constants import L_SCALE, P_SCALE, R_SCALE, V_SCALE
from core.obs_indices import ObsIdx
from core.visibility_engine import VisibilityEngine
from models.ppo_transformer_v2 import AgentV2

logger = logging.getLogger(__name__)


# --- DebugLoggerクラス ---
class DebugLogger:
    def __init__(self, enabled=False, log_interval_steps=100):
        self.enabled = bool(enabled)
        self.log_interval_steps = int(log_interval_steps)
        self._log_last_step = {}
        self._policy_src_logged = set()

    def print(self, message):
        if self.enabled:
            print(message)

    def print_throttled(self, key, message, current_step, force=False):
        if not self.enabled:
            return
        last = int(self._log_last_step.get(key, -10_000_000))
        if force or (int(current_step) - last) >= int(self.log_interval_steps):
            print(message)
            self._log_last_step[key] = int(current_step)

    def log_policy_source(self, agent_key, source, current_step, force=False):
        if not self.enabled:
            return
        k = (agent_key, source)
        if force or k not in self._policy_src_logged:
            print(f"[POLICY] {agent_key}: {source} @ {current_step}")
            self._policy_src_logged.add(k)

    def clear_policy_src_log(self):
        self._policy_src_logged.clear()


def _euler_z_to_quat(yaw):
    """Z軸回転角からクォータニオン文字列を生成。"""
    w = math.cos(yaw / 2.0)
    z = math.sin(yaw / 2.0)
    return f"{w:.6f} 0 0 {z:.6f}"


def _blocked_by_walls_numba(p1x, p1y, p2x, p2y, walls, margin):
    dx = p2x - p1x
    dy = p2y - p1y
    for i in range(walls.shape[0]):
        cx = walls[i, 0]
        cy = walls[i, 1]
        hx = walls[i, 2]
        hy = walls[i, 3]
        x_min = cx - hx - margin
        x_max = cx + hx + margin
        y_min = cy - hy - margin
        y_max = cy + hy + margin
        t0 = 0.0
        t1 = 1.0

        if abs(dx) < 1e-9:
            if p1x < x_min or p1x > x_max:
                continue
        else:
            inv_dx = 1.0 / dx
            tx1 = (x_min - p1x) * inv_dx
            tx2 = (x_max - p1x) * inv_dx
            t_enter = tx1 if tx1 < tx2 else tx2
            t_exit = tx2 if tx1 < tx2 else tx1
            if t_enter > t0:
                t0 = t_enter
            if t_exit < t1:
                t1 = t_exit
            if t0 > t1:
                continue

        if abs(dy) < 1e-9:
            if p1y < y_min or p1y > y_max:
                continue
        else:
            inv_dy = 1.0 / dy
            ty1 = (y_min - p1y) * inv_dy
            ty2 = (y_max - p1y) * inv_dy
            t_enter = ty1 if ty1 < ty2 else ty2
            t_exit = ty2 if ty1 < ty2 else ty1
            if t_enter > t0:
                t0 = t_enter
            if t_exit < t1:
                t1 = t_exit
            if t0 > t1:
                continue

        return False
    return False


class TeamCosEnv(gym.Env):
    # --- 統計バッファ初期化 ---
    def _init_debug_stats(self):
        self._debug_reward_buffer = []
        self._debug_hide_buffer = []
        self._wall_dist_buf = []
        self._debug_step_counter = 0
        self._debug_log_interval = getattr(self, "debug_logger", None) and getattr(self.debug_logger, "log_interval_steps", 100) or 100

    def _debug_collect_stats(self, reward, info):
        if not self.debug_mode:
            return
        self._debug_reward_buffer.append(reward)
        # 隠れ率: is_detected==False なら隠れているとみなす
        self._debug_hide_buffer.append(0 if info.get("is_detected", False) else 1)
        wd = info.get("wall_distance", None)
        if wd is not None:
            if isinstance(wd, (list, tuple, np.ndarray)):
                self._wall_dist_buf.extend([float(v) for v in wd])
            else:
                self._wall_dist_buf.append(float(wd))
        self._debug_step_counter += 1
        # log_intervalごとに統計出力
        if self._debug_step_counter % self._debug_log_interval == 0:
            self._debug_print_stats()

    def _debug_print_stats(self):
        if not self.debug_mode:
            return
        avg_reward = float(np.mean(self._debug_reward_buffer)) if self._debug_reward_buffer else 0.0
        hide_rate = float(np.mean(self._debug_hide_buffer)) if self._debug_hide_buffer else 0.0
        wd_arr = np.array(self._wall_dist_buf, dtype=np.float32) if self._wall_dist_buf else np.array([0.0])
        self.debug_logger.print(f"[DEBUG] Step={self.current_step} AvgR={avg_reward:.3f} HideRate={hide_rate:.2f} WallDist(mean/min/max)={wd_arr.mean():.3f}/{wd_arr.min():.3f}/{wd_arr.max():.3f}")
        self._debug_reward_buffer.clear()
        self._debug_hide_buffer.clear()
        self._wall_dist_buf.clear()


# (recovery file truncated here to keep size reasonable)
