
[runtime]
common = "{'action_repeat': 10, 'mode4_sdf_cell_size': 0.05, 'show_turn_lines': False, 'policy_source_log': False, 'policy_source_log_each_reset': False, 'debug_log_interval_steps': 200, 'use_custom_reward': True, 'rw_move_sat_penalty': 0.02, 'rw_wall_stick_penalty': 0.15, 'rw_wall_near_threshold': 0.18, 'rw_still_speed_threshold': 0.05, 'rw_hide_visible_near_penalty': 0.025, 'rw_hide_seeker_gaze_penalty': 0.03, 'rw_wall_avoid_penalty': 0.15, 'ramp_check_enabled': False, 'ramp_check_viewer': False, 'ramp_check_force_uphill': False, 'ramp_check_episodes': 3, 'ramp_check_steps': 220, 'wandb_enabled': True, 'num_envs': 10, 'move_sat_threshold': 1.0, 'turn_sat_threshold': 1.0, 'idle_speed_threshold': 0.1, 'move_incentive_speed_threshold': 0.3}"
optuna = "{'train_mode': True, 'use_viewer': False, 'training_target': 'hider', 'train_other_hider_policy': 'model_if_available', 'train_other_seeker_policy': 'model_if_available', 'npc_only_debug': False, 'auto_tune_hparams': False, 'wandb_run_name': 'wall_only_confirm_1M', 'rw_move_sat_penalty': 0.0}"
debug = "{'train_mode': False, 'debug_hider_policy': 'model_if_available', 'debug_seeker_policy': 'model_if_available', 'debug_deterministic_inference': False, 'debug_symmetric_hider_policy': False, 'npc_only_debug': False, 'auto_tune_hparams': False}"
train = "{'train_mode': True, 'use_viewer': False, 'training_target': 'hider', 'train_other_hider_policy': 'model_if_available', 'train_other_seeker_policy': 'model_if_available', 'npc_only_debug': False, 'auto_tune_hparams': False, 'wandb_run_name': 'wall_only_confirm_100M', 'rw_move_sat_penalty': 0.0}"
train1 = "{'train_mode': True, 'use_viewer': True, 'training_target': 'hider', 'train_other_hider_policy': 'model_if_available', 'train_other_seeker_policy': 'model_if_available', 'npc_only_debug': False, 'auto_tune_hparams': False, 'wandb_run_name': 'train1', 'rw_move_sat_penalty': 0.0, 'num_envs': 1}"
trainseeker = "{'train_mode': True, 'use_viewer': False, 'training_target': 'seeker', 'train_other_hider_policy': 'model_if_available', 'train_other_seeker_policy': 'model_if_available', 'npc_only_debug': False, 'auto_tune_hparams': False, 'wandb_run_name': 'wall_only_confirm_10M', 'rw_move_sat_penalty': 0.0}"
trainseeker_forRB = "{'train_mode': True, 'use_viewer': False, 'training_target': 'seeker', 'train_other_hider_policy': 'rule', 'train_other_seeker_policy': 'rule', 'npc_only_debug': False, 'auto_tune_hparams': False, 'wandb_run_name': 'wall_only_confirm_10M', 'rw_move_sat_penalty': 0.0}"

[base]
hidden_dim = 256
seq_len = 16

[defaults]
seeker = "{}"
hider = "{}"

[presets]
seeker = "{'s1_h2_b2_r1': {}, 's2_h3_b2_r3': {}}"
hider = "{'s1_h2_b2_r1': {}, 's2_h3_b2_r3': {}}"

[complexity]
rw_wall_avoid_penalty = 0.24852274025182242